# 行列積

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(a_ndarray)
print(b_ndarray)

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


【問題1】行列積を手計算する

<center><img src="631774820.jpg"　width=800px></center>

問題2】NumPyの関数による計算

In [3]:
mat_dot = np.matmul(a_ndarray, b_ndarray)
mat_dot

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題3】ある要素の計算を実装

In [6]:
result = []
for k, v, j in a_ndarray:
    tmp = []
    for n, m, l in b_ndarray.T:
        tmp.append(k * n + v * m + j * l)
    result.append(tmp)

result = np.array(result).reshape(3,3)
print(result)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題4】行列積を行う関数の作成

In [8]:
def mat_compute(A, B):
    result = []
    for k, v, j in a_ndarray:
        tmp = []
        for n, m, l in b_ndarray.T:
            tmp.append(k * n + v * m + j * l)
        result.append(tmp)

    result = np.array(result).reshape(3,3)
    return result

my = mat_compute(a_ndarray, b_ndarray)
print(my)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題5】計算が定義されない入力を判定する

In [15]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print(d_ndarray_)
print(e_ndarray)

[[-1  2  3]
 [ 4 -5  6]]
[[-9  8  7]
 [ 6 -5  4]]


In [16]:
def mat_compute(A, B):
    if A.shape[1] != B.shape[0]:
        print('行列間の次元が正しくない為計算できません。')
    
    elif A.shape[1] == B.shape[0]:
        result = []
        for k, v, j in a_ndarray:
            tmp = []
            for n, m, l in b_ndarray.T:
                tmp.append(k * n + v * m + j * l)
            result.append(tmp)

        result = np.array(result).reshape(3,3)
        return result
    
my = mat_compute(d_ndarray_, e_ndarray)

行列間の次元が正しくない為計算できません。


【問題6】転置

In [19]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]]).T

my = mat_compute(d_ndarray_, e_ndarray)
print(my)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
